### ISSUE TITLE
Output to pdf

### ISSUE THREAD

**Issue by Rebecza** [tilschaef/scRNA-seq#3]
**Concerning:** .rmd -> .pdf

I really like the pdf output, it is overall really nice!! (: 
(also the contents at the top, looks faancy)

There are some spots where the lines are going outside the page width, see below for an example. 

Is there a fix for this maybe (a wrapping setting)? Or does this need selection of the long lines in the rmd where this happens? 
It also sometimes happens in code chunks. 

![afbeelding](https://user-images.githubusercontent.com/56538023/108695396-882c8180-7500-11eb-9977-fffc8c085789.png)

**Comment by tilschaef** [comment]
That seems to be related to the way how the pdf is generated via pandoc since it's first converted to a latex document and then to pdf. The default environment does not break up long lines of text. However, it can be fixed by adding a custom preamble.tex file and include it in the document definition (https://bookdown.org/yihui/rmarkdown-cookbook/text-width.html). The pdf layout and code highlightning is now a bit different but clearer in my opinion. I added it in https://github.com/tilschaef/scRNA-seq/commit/f9c9fa20c6b239b03bb99fcd85dbf4dfa887f379

**Comment by tilschaef** [comment]
- commentstyle should be clearer (dark grey)!!
